package View.SuperUsuario.Empresa;

import Controller.SuperUsuarioController;
import Model.Usuario;
import View.SuperUsuario.InicioSesion;
import View.SuperUsuario.SuperUsuarioMainMenu;

import javax.swing.*;
import java.awt.event.ActionListener;

public class CrearNuevaEmpresaMenu extends JFrame {
    private Usuario superUsuario;
    public CrearNuevaEmpresaMenu(Usuario superUsuario) {
        this.superUsuario = superUsuario;
        initComponents();
        this.setLocationRelativeTo(null);
        lblNombreUsuario.setText(superUsuario.getNombre());

        btnHouse.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuperUsuarioMainMenu superUsuarioMainMenu = new SuperUsuarioMainMenu(superUsuario);
                superUsuarioMainMenu.setVisible(true);
                dispose();
            }
        });
        btnLogout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioSesion inicioSesion = new InicioSesion();
                inicioSesion.setVisible(true);
                dispose();
            }
        });

        btnCrear.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String ipNueva = txtFieldDocumento.getText();
                txtFieldDocumento.setText("");
                String nombreEmpresa = txtFieldEmpresa.getText();
                txtFieldEmpresa.setText("");
                SuperUsuarioController superUsuarioController = new SuperUsuarioController();
                superUsuarioController.addEmpresa(ipNueva,nombreEmpresa);
                JOptionPane.showMessageDialog(null, "Empresa creada "+nombreEmpresa);
            }
        });
    }
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            superiorBackground = new javax.swing.JPanel();
            lblLogo = new javax.swing.JLabel();
            lblNombreUsuario = new javax.swing.JLabel();
            lblTipoUsuario = new javax.swing.JLabel();
            lblImgSide = new javax.swing.JLabel();
            lblCrearSupervisor = new javax.swing.JLabel();
            DocLabel = new javax.swing.JLabel();
            lblEmpresa = new javax.swing.JLabel();
            txtFieldDocumento = new javax.swing.JTextField();
            txtFieldEmpresa = new javax.swing.JTextField();
            btnCrear = new javax.swing.JButton();
            btnHouse = new javax.swing.JButton();
            btnLogout = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(52, 33, 91));
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            setResizable(false);

            superiorBackground.setBackground(new java.awt.Color(52, 33, 91));

            lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Banner.png"))); // NOI18N

            lblNombreUsuario.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
            lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
            lblNombreUsuario.setText("Username");

            lblTipoUsuario.setFont(new java.awt.Font("FreeSans", 1, 36)); // NOI18N
            lblTipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
            lblTipoUsuario.setText("SUPERUSUARIO");

            javax.swing.GroupLayout superiorBackgroundLayout = new javax.swing.GroupLayout(superiorBackground);
            superiorBackground.setLayout(superiorBackgroundLayout);
            superiorBackgroundLayout.setHorizontalGroup(
                    superiorBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(superiorBackgroundLayout.createSequentialGroup()
                                    .addComponent(lblLogo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                                    .addGroup(superiorBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(16, 16, 16))
            );
            superiorBackgroundLayout.setVerticalGroup(
                    superiorBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(superiorBackgroundLayout.createSequentialGroup()
                                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, superiorBackgroundLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(lblTipoUsuario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblNombreUsuario)
                                    .addGap(12, 12, 12))
            );

            lblImgSide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Empresa.png"))); // NOI18N
            lblImgSide.setText("jLabel1");

            lblCrearSupervisor.setFont(new java.awt.Font("FreeSans", 1, 36)); // NOI18N
            lblCrearSupervisor.setText("Crear Nueva Empresa");

            DocLabel.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
            DocLabel.setText("NIT");

            lblEmpresa.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
            lblEmpresa.setText("Nombre");

            txtFieldDocumento.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtFieldDocumentoActionPerformed(evt);
                }
            });

            txtFieldEmpresa.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtFieldEmpresaActionPerformed(evt);
                }
            });

            btnCrear.setBackground(new java.awt.Color(209, 195, 237));
            btnCrear.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
            btnCrear.setText("Crear");
            btnCrear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            btnCrear.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCrearActionPerformed(evt);
                }
            });

            btnHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/casa.png"))); // NOI18N
            btnHouse.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            btnHouse.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnHouseActionPerformed(evt);
                }
            });

            btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logout.png"))); // NOI18N
            btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(superiorBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblImgSide, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(DocLabel)
                                                                    .addGap(249, 249, 249)
                                                                    .addComponent(lblEmpresa))
                                                            .addComponent(lblCrearSupervisor, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addGap(77, 77, 77))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                    .addComponent(txtFieldDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addGap(49, 49, 49)
                                                                                    .addComponent(txtFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addGap(207, 207, 207))))
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(btnHouse)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addComponent(btnLogout)))))
                                    .addGap(39, 39, 39))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addComponent(superiorBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lblCrearSupervisor)
                                                    .addGap(62, 62, 62)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(DocLabel)
                                                            .addComponent(lblEmpresa))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(txtFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtFieldDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(54, 54, 54)
                                                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(99, 99, 99)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(btnHouse))
                                                    .addGap(15, 15, 15))
                                            .addComponent(lblImgSide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
            );

            pack();
        }// </editor-fold>

        private void txtFieldEmpresaActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void btnHouseActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void txtFieldDocumentoActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }


        // Variables declaration - do not modify
        private javax.swing.JLabel DocLabel;
        private javax.swing.JButton btnCrear;
        private javax.swing.JButton btnHouse;
        private javax.swing.JButton btnLogout;
        private javax.swing.JLabel lblCrearSupervisor;
        private javax.swing.JLabel lblEmpresa;
        private javax.swing.JLabel lblImgSide;
        private javax.swing.JLabel lblLogo;
        private javax.swing.JLabel lblNombreUsuario;
        private javax.swing.JLabel lblTipoUsuario;
        private javax.swing.JPanel superiorBackground;
        private javax.swing.JTextField txtFieldDocumento;
        private javax.swing.JTextField txtFieldEmpresa;
        // End of variables declaration
}

